# Config

username : "Admin"
password : "admin123"
firstname : "Evanchalin"
lastname : "C K"
dob : "1994-03-28"
license_no: "1234 5678 9012"
license_exp_date : "2023-12-31"
id : "9537"
join_date : "2023-07-01"

